import { chromium } from "playwright";
const b = await chromium.launch();
const p = await (await b.newContext()).newPage();
const logs = [];
p.on("console", m => logs.push([m.type(), m.text()]));
p.on("pageerror", e => logs.push(["pageerror", e.message + "\n" + (e.stack||"").split("\n").slice(0,4).join("\n")]));
await p.goto(process.argv[2], { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
const bad = logs.filter(([t]) => t === "error" || t === "warning" || t === "pageerror");
console.log(`total console messages: ${logs.length}, errors/warnings: ${bad.length}\n`);
for (const [t, m] of bad) console.log(`[${t}] ${m.slice(0, 700)}\n`);
if (!bad.length) console.log("no errors or warnings");
await b.close();
